// Objective-C API for talking to github.com/taurusgroup/frost-ed25519/ed25519 Go package.
//   gobind -lang=objc github.com/taurusgroup/frost-ed25519/ed25519
//
// File is generated by gobind. Do not edit.

#ifndef __Ed25519_H__
#define __Ed25519_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Ed25519FKeyGenOutput;
@class Ed25519KeyGenOutState;
@class Ed25519KeyGenOutState2;
@class Ed25519MPCSignatureOutState;

@interface Ed25519FKeyGenOutput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field FKeyGenOutput.Secrets with unsupported type: map[github.com/taurusgroup/frost-ed25519/pkg/frost/party.ID]*github.com/taurusgroup/frost-ed25519/pkg/eddsa.SecretShare

// skipped field FKeyGenOutput.Shares with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/eddsa.Public

@end

@interface Ed25519KeyGenOutState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field KeyGenOutState.State with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/state.State

// skipped field KeyGenOutState.Output with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/frost/keygen.Output

// skipped field KeyGenOutState.Message1 with unsupported type: [][]byte

// skipped field KeyGenOutState.Message2 with unsupported type: [][]byte

@end

@interface Ed25519KeyGenOutState2 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field KeyGenOutState2.State with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/state.State

// skipped field KeyGenOutState2.Output with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/frost/keygen.Output

@property (nonatomic) NSString* _Nonnull message1;
@property (nonatomic) NSString* _Nonnull message2;
@end

@interface Ed25519MPCSignatureOutState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field MPCSignatureOutState.State with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/state.State

// skipped field MPCSignatureOutState.Output with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/frost/sign.Output

// skipped field MPCSignatureOutState.GroupKey with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/eddsa.PublicKey

// skipped field MPCSignatureOutState.Message1 with unsupported type: [][]byte

// skipped field MPCSignatureOutState.Message2 with unsupported type: [][]byte

@end

// skipped function DKGSlice with unsupported parameter or return types


// skipped function KeyGenDemoV2 with unsupported parameter or return types


// skipped function KeygenMsg2String with unsupported parameter or return types


// skipped function KeygenString2Msg with unsupported parameter or return types


// skipped function MPCPartSignRound0 with unsupported parameter or return types


// skipped function MPCPartSignRound1 with unsupported parameter or return types


// skipped function MPCPartSignRound2 with unsupported parameter or return types


// skipped function SliceKeyGenRound0 with unsupported parameter or return types


// skipped function SliceKeyGenRound1 with unsupported parameter or return types


// skipped function SliceKeyGenRound2 with unsupported parameter or return types


// skipped function VerifySignature with unsupported parameter or return types


#endif
