// Objective-C API for talking to github.com/taurusgroup/frost-ed25519/ed25519 Go package.
//   gobind -lang=objc github.com/taurusgroup/frost-ed25519/ed25519
//
// File is generated by gobind. Do not edit.

#ifndef __Ed25519_H__
#define __Ed25519_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Ed25519CombinedOutput;
@class Ed25519Secret;
@class Ed25519Shares;

@interface Ed25519CombinedOutput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field CombinedOutput.Secrets with unsupported type: map[string]github.com/taurusgroup/frost-ed25519/ed25519.Secret

// skipped field CombinedOutput.Shares with unsupported type: github.com/taurusgroup/frost-ed25519/ed25519.Shares

@end

@interface Ed25519Secret : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull secret;
@end

@interface Ed25519Shares : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long t;
@property (nonatomic) NSString* _Nonnull groupKey;
// skipped field Shares.Shares with unsupported type: map[string]string

@end

FOUNDATION_EXPORT NSString* _Nonnull Ed25519SliceKeygen(long t, long n);

FOUNDATION_EXPORT NSString* _Nonnull Ed25519VerifyKeys(NSString* _Nullable keys, NSString* _Nullable msg);

#endif
