
// Objective-C API for talking to the following Go packages
//
//	github.com/taurusgroup/frost-ed25519/ed25519
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ed25519_FRAMEWORK_H__
#define __Ed25519_FRAMEWORK_H__

#include "Ed25519.objc.h"
#include "Universe.objc.h"

#endif
